// <auto-generated />
using System;
using LNURLSharp.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LNURLSharp.Migrations
{
    [DbContext(typeof(LNURLContext))]
    [Migration("20211025025602_WithdrawSetup2")]
    partial class WithdrawSetup2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("LNURLSharp.DB.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHash")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Expired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FallbackAddr")
                        .HasColumnType("TEXT");

                    b.Property<string>("LNDServerPubkey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payreq")
                        .HasColumnType("TEXT");

                    b.Property<string>("RHashBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("LNDServerPubkey");

                    b.HasIndex("Payreq")
                        .IsUnique();

                    b.HasIndex("Username");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LNURLSharp.DB.LNDServer", b =>
                {
                    b.Property<string>("Pubkey")
                        .HasColumnType("TEXT");

                    b.HasKey("Pubkey");

                    b.HasIndex("Pubkey")
                        .IsUnique();

                    b.ToTable("LNDServers");
                });

            modelBuilder.Entity("LNURLSharp.DB.WithdrawSetup", b =>
                {
                    b.Property<int>("WithdrawSetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("K1")
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxWithdrawable")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinWithdrawable")
                        .HasColumnType("INTEGER");

                    b.HasKey("WithdrawSetupId");

                    b.ToTable("WithdrawSetups");
                });

            modelBuilder.Entity("LNURLSharp.DB.Invoice", b =>
                {
                    b.HasOne("LNURLSharp.DB.LNDServer", "LNDServer")
                        .WithMany("Invoices")
                        .HasForeignKey("LNDServerPubkey");

                    b.Navigation("LNDServer");
                });

            modelBuilder.Entity("LNURLSharp.DB.LNDServer", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
