// <auto-generated />
using System;
using LNURLSharp.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LNURLSharp.Migrations
{
    [DbContext(typeof(LNURLContext))]
    partial class LNURLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("LNURLSharp.DB.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LNDServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payreq")
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("LNDServerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LNURLSharp.DB.LNDServer", b =>
                {
                    b.Property<int>("LNDServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pubkey")
                        .HasColumnType("TEXT");

                    b.HasKey("LNDServerId");

                    b.ToTable("LNDServers");
                });

            modelBuilder.Entity("LNURLSharp.DB.PaySetup", b =>
                {
                    b.Property<int>("PaySetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("PaySetupId");

                    b.ToTable("PaySetups");
                });

            modelBuilder.Entity("LNURLSharp.DB.Invoice", b =>
                {
                    b.HasOne("LNURLSharp.DB.LNDServer", "LNDServer")
                        .WithMany("Invoices")
                        .HasForeignKey("LNDServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LNDServer");
                });

            modelBuilder.Entity("LNURLSharp.DB.LNDServer", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
